version: 2
groups:
  code-review:
    approve_by_comment:
      approve_regex: ^Approved
      enabled: true
      reject_regex: ^Disapproved
    required: 1
    reset_on_push:
      enabled: false
    users:
    - yoginth
